version: '3.8'
services:
  app:
    build: .
    container_name: challenge_app
    ports:
      - '4000:4000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: challenge_redis
    ports:
      - '6379:6379'